language: Rust
cache: cargo
sudo: false
rust:
- stable
- beta
- nightly
script:
- cargo test 
# Verify that reading from stdin and writing from stdout actually works
- GLUON_TEST_REMOTE_SERVER=1 cargo test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1f97acdae0f19676b03b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
