[package]
name = "gluon_language-server"
version = "0.2.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/gluon-lang/gluon_language-server"

[workspace]

[[bin]]
name = "gluon_debugger"
path = "src/debugger.rs"

[[bin]]
name = "gluon_language-server"
path = "src/main.rs"

[dependencies]
clap = "2.19.0"

log = "0.3.6"
env_logger = "0.3.3"

url = "1.2.0"

jsonrpc-core = "6.0.0"
futures = "0.1.0"

serde = "0.9.6"
serde_json = "0.9.0"

languageserver-types = "0.7.0"
debugserver-types = "0.2.0"

[dependencies.gluon]
version = "0.3.0"
# Don't include the repl
default-features = false

[dev-dependencies]
lazy_static = "0.2.2"
