[package]
name = "gluon_language-server"
version = "0.2.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/gluon-lang/gluon_language-server"

[workspace]

[dependencies]
log = "0.3.6"
env_logger = "0.3.3"

url = "1.2.0"

jsonrpc-core = "5.0.0"
futures = "0.1.0"

serde = "0.8.11"
serde_json = "0.8.0"

languageserver-types =  "0.4.0"

[dependencies.gluon]
git = "https://github.com/Marwes/gluon"
branch = "debugger"
# Don't include the repl
default-features = false
