[package]
name = "gluon_language-server"
version = "0.6.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/gluon-lang/gluon_language-server"

[workspace]

[[bin]]
name = "gluon_debugger"
path = "src/debugger.rs"

[[bin]]
name = "gluon_language-server"
path = "src/main.rs"

[lib]
name = "gluon_language_server"
path = "src/lib.rs"

[dependencies]
clap = "2.19.0"

log = "0.3.6"
env_logger = "0.3.3"

url = "1.2.0"
url_serde = "0.2.0"

combine = "3.0.0-alpha.4"

jsonrpc-core = "7.0.0"
futures = "0.1.0"
futures-cpupool = "0.1.0"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
bytes = "0.4.5"
fibers = "0.1.8"

serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"

languageserver-types = { path = "../languageserver-types" }
debugserver-types = "0.3.0"

gluon = "0.6.1"
gluon_completion = "0.6.1"
gluon_format = "0.6.1"

[dev-dependencies]
pretty_assertions = "0.2.0"

[patch.crates-io]
gluon_base = { git = "https://github.com/gluon-lang/gluon", branch = "master" }
gluon_parser = { git = "https://github.com/gluon-lang/gluon", branch = "master"  }
gluon_check = { git = "https://github.com/gluon-lang/gluon", branch = "master"  }
gluon_vm = { git = "https://github.com/gluon-lang/gluon", branch = "master"  }
gluon = { git = "https://github.com/gluon-lang/gluon", branch = "master"  }
gluon_completion = { git = "https://github.com/gluon-lang/gluon", branch = "master"  }
gluon_format = { git = "https://github.com/gluon-lang/gluon", branch = "master"  }
