[package]
name = "gluon_language-server"
version = "0.7.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/gluon-lang/gluon_language-server"

[workspace]

[[bin]]
name = "gluon_debugger"
path = "src/debugger.rs"

[[bin]]
name = "gluon_language-server"
path = "src/main.rs"

[lib]
name = "gluon_language_server"
path = "src/lib.rs"

[dependencies]
clap = "2.19.0"

log = "0.3.6"
env_logger = "0.3.3"

url = "1.2.0"
url_serde = "0.2.0"

combine = "=3.0.0-beta.1"

jsonrpc-core = "8.0.1"
futures = "0.1.0"
futures-cpupool = "0.1.0"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
bytes = "0.4.5"

serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"

languageserver-types = "0.20.0"
debugserver-types = "0.4.0"

gluon = "0.7.1"
gluon_completion = "0.7.1"
gluon_format = "0.7.1"

[dev-dependencies]
pretty_assertions = "0.2.0"
partial-io = { version = "0.2.5", features = ["tokio", "quickcheck"] }
quickcheck = "0.4.1"

